# Site settings
title: HeCoSiRe Blog
email: hello@hecosire.com
description: > # this means to ignore newlines until "baseurl:"
  HeCoSiRe is a health tracker. 
  You can use it to track how you feel and get insight into your health.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.hecosire.com" # the base hostname & protocol for your site
twitter_username: hecosire
github_username:  hecosire

# Build settings
markdown: kramdown
